[project]
name = "illegal-mining-risk-detection"
version = "0.1.0"
description = "Proyecto de Data Science y análisis geoespacial para detección de riesgo de minería ilegal en Perú."
requires-python = ">=3.10"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "jupyter",
    "geopandas",
]